const fs = require('fs');
const path = require('path');

const q = (id, topic, diff, stem, optT, optF1, optF2, optF3, exp) => ({
  importId: "ANDE-M16-ANAT-" + id,
  stem,
  subjectSlug: "anatomy",
  topicSlug: topic,
  examRelevance: 8,
  difficulty: diff,
  questionType: "SINGLE_BEST_ANSWER",
  provenance: "ORIGINAL",
  exam: "NEET_PG_INI_CET",
  options: [
    { text: optT, isCorrect: true },
    { text: optF1, isCorrect: false },
    { text: optF2, isCorrect: false },
    { text: optF3, isCorrect: false }
  ].sort(() => Math.random() - 0.5),
  explanation: exp
});

const data = [
  // 1-5: anatomy-general-anatomy
  q("001", "anatomy-general-anatomy", "EASY", "Which of the following joint types best describes the sagittal suture of the adult human skull?", "Fibrous joint", "Synovial joint", "Primary cartilaginous joint", "Secondary cartilaginous joint", "The sagittal suture is a fibrous joint. Sutures are connected by dense connective tissue and are generally immovable (synarthroses)."),
  q("002", "anatomy-general-anatomy", "MEDIUM", "Which of the following structures is an example of a traction epiphysis?", "Greater trochanter", "Head of the femur", "Lower end of the radius", "Condyles of the tibia", "Traction epiphyses are formed where muscles attach to bones. The greater trochanter is a traction epiphysis for the gluteal muscles. The head of the femur is a pressure epiphysis."),
  q("003", "anatomy-general-anatomy", "MEDIUM", "Which type of cartilage forms the articular surfaces of most synovial joints in the human body?", "Hyaline cartilage", "Elastic cartilage", "Fibrocartilage", "Reticular cartilage", "Hyaline cartilage is the most abundant cartilage and forms the articular surfaces of most synovial joints. Fibrocartilage is found in intervertebral discs and the pubic symphysis."),
  q("004", "anatomy-general-anatomy", "HARD", "In human muscle architecture, which of the following is a classic example of a multipennate muscle designed to generate high force over a short range of movement?", "Deltoid", "Sartorius", "Biceps brachii", "Rectus abdominis", "The deltoid is a multipennate muscle, allowing a large number of fibers to be packed in a small area, generating high force. Sartorius is parallel, biceps is fusiform."),
  q("005", "anatomy-general-anatomy", "HARD", "Which of the following vascular arrangements best describes the functional end arteries found within the central nervous system?", "Arteries that supply distinct tissue areas but lack sufficient anastomoses to maintain viability if occluded", "Arteries with extensive precapillary anastomoses", "Arteries that possess large arteriovenous shunts bypassing capillary beds", "Arteries that communicate freely at the macrovascular level but not at the microvascular level", "Functional end arteries do anastomose, but the anastomoses are insufficient to keep the tissue alive if occluded. Occlusion leads to infarction."),

  // 6-10: anatomy-lower-limb
  q("006", "anatomy-lower-limb", "EASY", "A 35-year-old male sustains a fracture of the fibular neck. He subsequently develops foot drop and a high-stepping gait. Which nerve is most likely injured?", "Common peroneal nerve", "Tibial nerve", "Sural nerve", "Saphenous nerve", "The common peroneal (fibular) nerve wraps around the fibular neck and is vulnerable here. Injury paralyzes the anterior/lateral compartments, causing foot drop."),
  q("007", "anatomy-lower-limb", "MEDIUM", "A patient exhibits a positive Trendelenburg sign on the right side when asked to stand on her right leg. Which nerve is compromised?", "Right superior gluteal nerve", "Right inferior gluteal nerve", "Right obturator nerve", "Right femoral nerve", "The superior gluteal nerve supplies gluteus medius and minimus, responsible for stabilizing the pelvis. Weakness leads to a positive Trendelenburg sign on the affected side."),
  q("008", "anatomy-lower-limb", "MEDIUM", "Which muscle is primarily responsible for 'unlocking' the extended knee joint by laterally rotating the femur on the fixed tibia?", "Popliteus", "Semimembranosus", "Biceps femoris", "Plantaris", "The popliteus unlocks the knee joint by laterally rotating the femur on the fixed tibia (or medially rotating the tibia on unplanted femur) to initiate flexion."),
  q("009", "anatomy-lower-limb", "HARD", "Which of the following arteries does NOT typically participate in the cruciate anastomosis of the thigh?", "Superior gluteal artery", "Inferior gluteal artery", "Medial circumflex femoral artery", "First perforating artery", "The cruciate anastomosis includes the inferior gluteal, medial circumflex, lateral circumflex, and first perforating arteries. The superior gluteal artery does not participate."),
  q("010", "anatomy-lower-limb", "HARD", "A 50-year-old woman undergoes stripping of the great saphenous vein. Postoperatively, she complains of numbness along the medial border of her foot. Which nerve was injured?", "Saphenous nerve", "Sural nerve", "Superficial peroneal nerve", "Deep peroneal nerve", "The saphenous nerve accompanies the great saphenous vein in the lower leg and can be injured during vein stripping, causing numbness on the medial aspect of the foot."),

  // 11-15: anatomy-thorax
  q("011", "anatomy-thorax", "EASY", "The sternal angle (of Louis) corresponds to the level of the intervertebral disc between which two thoracic vertebrae?", "T4 and T5", "T2 and T3", "T6 and T7", "T8 and T9", "The sternal angle lies at the intervertebral disc between T4 and T5. It marks the tracheal bifurcation, aortic arch ends, and superior/inferior mediastinum boundary."),
  q("012", "anatomy-thorax", "MEDIUM", "In the posterior mediastinum, the azygos vein arches over the root of the right lung to terminate directly into which vascular structure?", "Superior vena cava", "Inferior vena cava", "Right brachiocephalic vein", "Right atrium", "The azygos vein ascends, passes behind the right lung root, and arches over the right main bronchus to drain into the superior vena cava."),
  q("013", "anatomy-thorax", "MEDIUM", "An aspirated foreign body is more likely to enter the right main bronchus than the left because the right bronchus is:", "Wider, shorter, and more vertical than the left", "Narrower, longer, and more horizontal than the left", "Originating at a higher vertebral level than the left", "Deflected strongly by the carina towards the right side", "The right main bronchus is wider, shorter, and more vertical, making it a more direct continuation of the trachea and the most common site for aspirated foreign bodies."),
  q("014", "anatomy-thorax", "HARD", "Which of the following structures descends through the posterior mediastinum and passes through the aortic hiatus of the diaphragm?", "Thoracic duct", "Phrenic nerve", "Esophagus", "Sympathetic trunk", "The thoracic duct lies in the posterior mediastinum and enters the thorax through the aortic hiatus of the diaphragm along with the descending aorta and azygos vein."),
  q("015", "anatomy-thorax", "HARD", "In a patient with right-dominant coronary circulation, the artery supplying the atrioventricular (AV) node typically arises from which vessel?", "Right coronary artery", "Left anterior descending artery", "Left circumflex artery", "Coronary sinus", "In right-dominant circulation (~80% of individuals), the right coronary artery supplies the posterior descending artery and also gives off the AV nodal branch."),

  // 16-20: anatomy-abdomen
  q("016", "anatomy-abdomen", "EASY", "Early periumbilical pain in acute appendicitis is referred visceral pain carried by afferent fibers entering the spinal cord at which dermatomal level?", "T10", "T8", "T12", "L2", "The appendix is supplied by T10 sympathetic fibers. Referred pain is classically felt in the T10 dermatome, which surrounds the umbilicus."),
  q("017", "anatomy-abdomen", "MEDIUM", "During an open repair, a surgeon identifies a hernia sac protruding through Hesselbach's triangle, medial to the inferior epigastric vessels. What type of hernia is this?", "Direct inguinal hernia", "Indirect inguinal hernia", "Femoral hernia", "Spigelian hernia", "Direct inguinal hernias protrude medial to the inferior epigastric vessels through Hesselbach's triangle. Indirect hernias pass lateral to these vessels through the deep inguinal ring."),
  q("018", "anatomy-abdomen", "MEDIUM", "Superior mesenteric artery (SMA) syndrome involves the acute mechanical compression of which structure between the SMA and the abdominal aorta?", "Third part of the duodenum", "First part of the duodenum", "Second part of the duodenum", "Pylorus of the stomach", "The third (transverse) part of the duodenum crosses the aorta directly behind the superior mesenteric artery, making it vulnerable to compression in SMA syndrome."),
  q("019", "anatomy-abdomen", "HARD", "Caput medusae in a cirrhotic patient results from the engorgement of porto-systemic anastomoses between the paraumbilical veins and which venous system?", "Superficial epigastric veins", "Inferior mesenteric veins", "Lumbar veins", "Hepatic veins", "Caput medusae forms when portal hypertension forces blood backward through paraumbilical veins into the superficial epigastric veins of the systemic circulation."),
  q("020", "anatomy-abdomen", "HARD", "When performing the Pringle maneuver (clamping the hepatoduodenal ligament), which structure forms the immediate posterior boundary of the epiploic foramen?", "Inferior vena cava", "Abdominal aorta", "Right crus of the diaphragm", "Portal vein", "The epiploic foramen of Winslow is bounded anteriorly by the hepatoduodenal ligament and posteriorly by the inferior vena cava."),

  // 21-25: anatomy-pelvis-and-perineum
  q("021", "anatomy-pelvis-and-perineum", "EASY", "Excluding the external urethral meatus, which portion of the male urethra is anatomically the narrowest and least distensible?", "Membranous urethra", "Prostatic urethra", "Bulbar urethra", "Penile (spongy) urethra", "The membranous urethra passes through the deep perineal pouch and perineal membrane. It is the narrowest, shortest, and least distensible part, making it prone to catheter injury."),
  q("022", "anatomy-pelvis-and-perineum", "MEDIUM", "A transvaginal pudendal nerve block is administered to a woman in labor. Which palpable bony landmark is used to guide the injection needle?", "Ischial spine", "Ischial tuberosity", "Pubic symphysis", "Posterior superior iliac spine", "The pudendal nerve crosses the posterior aspect of the sacrospinous ligament near the ischial spine, which is palpated transvaginally to guide the block."),
  q("023", "anatomy-pelvis-and-perineum", "MEDIUM", "During a radical hysterectomy, the ureter is most vulnerable to iatrogenic injury where it passes directly under the uterine artery near which structure?", "The lateral fornix of the vagina", "The infundibulopelvic ligament", "The round ligament of the uterus", "The ovarian ligament", "The ureter passes inferior to the uterine artery ('water under the bridge') near the lateral vaginal fornix and cervix, making it highly susceptible to injury during ligation."),
  q("024", "anatomy-pelvis-and-perineum", "HARD", "Carcinoma of the prostate most frequently spreads via the lymphatic system first to which group of lymph nodes?", "Internal iliac nodes", "Superficial inguinal nodes", "Deep inguinal nodes", "Lumbar (para-aortic) nodes", "Primary lymphatic drainage of the prostate goes to the internal iliac and sacral lymph nodes, representing the first sites of regional metastasis."),
  q("025", "anatomy-pelvis-and-perineum", "HARD", "Which of the following structures is located strictly within the deep perineal pouch in males?", "Bulbourethral (Cowper's) glands", "Bulbospongiosus muscle", "Crura of the penis", "Greater vestibular (Bartholin's) glands", "The deep perineal pouch in males contains the membranous urethra, deep transverse perineal muscles, sphincter urethrae, and bulbourethral glands."),

  // 26-30: anatomy-head-and-neck
  q("026", "anatomy-head-and-neck", "EASY", "A man presents with sudden inability to close his right eye, loss of right forehead wrinkles, and drooping of the right corner of his mouth. Which cranial nerve is affected?", "Facial nerve", "Trigeminal nerve", "Glossopharyngeal nerve", "Vagus nerve", "Bell's palsy is a lower motor neuron lesion of the facial nerve (CN VII), paralyzing all muscles of facial expression on the ipsilateral side."),
  q("027", "anatomy-head-and-neck", "MEDIUM", "Infections in the 'danger triangle of the face' spread retrogradely to the cavernous sinus primarily via communications between the facial vein and which veins?", "Superior and inferior ophthalmic veins", "Retromandibular veins", "Internal jugular veins", "Maxillary veins", "The facial vein communicates with the ophthalmic veins, which drain into the cavernous sinus. The lack of valves permits retrograde spread of infection."),
  q("028", "anatomy-head-and-neck", "MEDIUM", "Which of the following muscles of mastication is primarily responsible for depressing the mandible to open the mouth?", "Lateral pterygoid", "Masseter", "Medial pterygoid", "Temporalis", "The lateral pterygoid is the only muscle of mastication that depresses the mandible (opens the mouth). The other three elevate it."),
  q("029", "anatomy-head-and-neck", "HARD", "A Pancoast tumor at the apex of the right lung causes right-sided ptosis, miosis, and anhidrosis. This is due to the tumor's compression of which structure?", "Cervical sympathetic chain", "Phrenic nerve", "Vagus nerve", "Recurrent laryngeal nerve", "Invasion of the cervical sympathetic chain leads to ipsilateral Horner's syndrome (ptosis, miosis, anhidrosis)."),
  q("030", "anatomy-head-and-neck", "HARD", "Frey's syndrome (sweating/flushing of the cheek while eating) occurs after parotid surgery due to aberrant regeneration of parasympathetic fibers into the territory of which nerve?", "Auriculotemporal nerve", "Greater auricular nerve", "Facial nerve", "Buccal nerve", "Damaged parasympathetic secretomotor fibers aberrantly regenerate and join sympathetic pathways in the auriculotemporal nerve, causing gustatory sweating."),

  // 31-35: anatomy-neuroanatomy
  q("031", "anatomy-neuroanatomy", "EASY", "Cerebrospinal fluid (CSF) circulates through the ventricles to protect the brain. It is primarily produced by which of the following structures?", "Choroid plexus", "Arachnoid granulations", "Ependymal cells lining the central canal", "Pia mater", "CSF is actively secreted by the choroid plexus located within the lateral, third, and fourth ventricles. It is resorbed by arachnoid granulations."),
  q("032", "anatomy-neuroanatomy", "MEDIUM", "A knife wound causes a clean right-sided hemisection of the spinal cord at T10. Which clinical finding is expected below the level of the lesion?", "Contralateral loss of pain and temperature sensation", "Contralateral loss of proprioception and vibration", "Ipsilateral loss of pain and temperature sensation", "Contralateral spastic paralysis", "Brown-Sequard syndrome causes ipsilateral spastic paralysis and loss of proprioception, but contralateral loss of pain and temperature due to spinothalamic tract decussation."),
  q("033", "anatomy-neuroanatomy", "MEDIUM", "A stroke patient fully understands instructions but produces halting, non-fluent, and effortful speech. The lesion most likely affects which area?", "Inferior frontal gyrus (Broca's area)", "Superior temporal gyrus (Wernicke's area)", "Precentral gyrus (Primary motor cortex)", "Angular gyrus", "Broca's area in the dominant inferior frontal gyrus coordinates speech production. A lesion here causes expressive, non-fluent aphasia with preserved comprehension."),
  q("034", "anatomy-neuroanatomy", "HARD", "Wallenberg syndrome (vertigo, dysphagia, right facial numbness, left body numbness, right Horner's syndrome) is most likely due to occlusion of which artery?", "Posterior inferior cerebellar artery (PICA)", "Anterior inferior cerebellar artery (AICA)", "Basilar artery", "Superior cerebellar artery", "Lateral Medullary Syndrome is classically caused by occlusion of the PICA or vertebral artery, leading to crossed sensory signs and bulbar weakness."),
  q("035", "anatomy-neuroanatomy", "HARD", "Weber's syndrome (ipsilateral oculomotor nerve palsy and contralateral spastic hemiparesis) indicates a lesion in which specific region of the brainstem?", "Midbrain", "Medulla oblongata", "Pons", "Thalamus", "Weber's syndrome is a midbrain infarct affecting the cerebral peduncle and the exiting fascicles of the oculomotor nerve (CN III)."),

  // 36-40: anatomy-embryology
  q("036", "anatomy-embryology", "EASY", "The mandible and the muscles of mastication are derived from which embryonic pharyngeal arch?", "First pharyngeal arch", "Second pharyngeal arch", "Third pharyngeal arch", "Fourth pharyngeal arch", "The first pharyngeal (mandibular) arch gives rise to the mandible, maxilla, malleus, incus, and the muscles of mastication, innervated by CN V3."),
  q("037", "anatomy-embryology", "MEDIUM", "The fundamental embryological defect that leads to the four classic features of Tetralogy of Fallot is the anterosuperior displacement of which structure?", "Infundibular (conotruncal) septum", "Septum primum", "Endocardial cushions", "Aorticopulmonary septum", "Anterosuperior displacement of the infundibular septum unequally divides the truncus arteriosus, causing pulmonary stenosis, VSD, and overriding aorta."),
  q("038", "anatomy-embryology", "MEDIUM", "The uncinate process and the inferior part of the head of the pancreas are derived from which embryonic structure?", "Ventral pancreatic bud", "Dorsal pancreatic bud", "Hepatic diverticulum", "Midgut loop", "The ventral pancreatic bud rotates dorsally to fuse with the dorsal bud. It forms the uncinate process and the inferior head of the pancreas."),
  q("039", "anatomy-embryology", "HARD", "Meckel's diverticulum, which can contain ectopic gastric mucosa and cause painless lower GI bleeding, is a persistent remnant of which embryonic structure?", "Vitelline (omphalomesenteric) duct", "Urachus", "Allantois", "Cloaca", "Meckel's diverticulum is a true diverticulum that is a remnant of the vitelline duct connecting the embryonic midgut to the yolk sac."),
  q("040", "anatomy-embryology", "HARD", "Which of the following embryonic structures does NOT contribute to the normal development of the diaphragm?", "Urogenital ridge", "Septum transversum", "Pleuroperitoneal folds", "Dorsal mesentery of the esophagus", "The diaphragm forms from the septum transversum, pleuroperitoneal folds, dorsal mesentery of the esophagus, and body wall mesoderm. The urogenital ridge does not contribute."),

  // 41-45: anatomy-histology
  q("041", "anatomy-histology", "EASY", "The mucosal lining of the human urinary bladder is composed of which specific type of epithelium to accommodate significant distension?", "Transitional epithelium (urothelium)", "Stratified squamous non-keratinized epithelium", "Pseudostratified ciliated columnar epithelium", "Simple cuboidal epithelium", "The urinary tract, from renal calyces to proximal urethra, is lined by transitional epithelium, allowing stretching without tearing."),
  q("042", "anatomy-histology", "MEDIUM", "Within the fundic glands of the stomach, which specific cells are responsible for the secretion of both hydrochloric acid (HCl) and intrinsic factor?", "Parietal (oxyntic) cells", "Chief cells", "Mucous neck cells", "Enteroendocrine (G) cells", "Parietal cells secrete HCl for protein digestion and intrinsic factor, which is essential for vitamin B12 absorption in the terminal ileum."),
  q("043", "anatomy-histology", "MEDIUM", "In the microscopic architecture of the liver, what is the primary function or identity of the perisinusoidal space (of Disse)?", "It is the gap between fenestrated sinusoidal endothelial cells and hepatocytes, facilitating plasma exchange.", "It is the space between adjacent hepatocytes where bile canaliculi form.", "It is the space containing the portal triad within the hepatic lobule.", "It is the primary site of hematopoiesis in the adult liver.", "The space of Disse lies between the sinusoids and hepatocytes. It contains blood plasma, facilitating metabolic exchange, and houses hepatic stellate cells."),
  q("044", "anatomy-histology", "HARD", "Which epidermal layer is prominently visible in thick skin (palms/soles) but is generally considered absent in thin skin?", "Stratum lucidum", "Stratum basale", "Stratum spinosum", "Stratum granulosum", "The stratum lucidum is a clear, translucent layer situated between the stratum granulosum and stratum corneum, found almost exclusively in thick skin."),
  q("045", "anatomy-histology", "HARD", "In chronic left-sided heart failure, alveolar macrophages phagocytize red blood cells. These 'heart failure cells' are packed with which substance?", "Hemosiderin", "Lipofuscin", "Melanin", "Surfactant", "Elevated pulmonary pressure causes erythrocytes to leak into alveoli. Macrophages phagocytize them, breaking down hemoglobin into hemosiderin pigment."),

  // 46-50: anatomy-genetics-developmental-anatomy
  q("046", "anatomy-genetics-developmental-anatomy", "EASY", "A newborn presents with upslanting palpebral fissures, a single palmar crease, and an AV septal defect. Which chromosomal abnormality is most likely?", "Trisomy 21", "Trisomy 13", "Trisomy 18", "Monosomy X", "Down syndrome (Trisomy 21) is the most common chromosomal anomaly in liveborns, characterized by these classic facial features and heart defects."),
  q("047", "anatomy-genetics-developmental-anatomy", "MEDIUM", "A 16-year-old female is evaluated for primary amenorrhea, short stature, a webbed neck, and a broad chest. What is her most likely karyotype?", "45, X", "46, XX", "47, XXX", "47, XXY", "Turner syndrome (45, X) affects females and presents with short stature, webbed neck, shield chest, and streak ovaries leading to primary amenorrhea."),
  q("048", "anatomy-genetics-developmental-anatomy", "MEDIUM", "A 25-year-old tall male with gynecomastia, small firm testes, and infertility is evaluated. What is his most likely karyotype?", "47, XXY", "46, XY", "47, XYY", "46, XX", "Klinefelter syndrome (47, XXY) classically presents in males with tall stature, hypogonadism, gynecomastia, and infertility due to azoospermia."),
  q("049", "anatomy-genetics-developmental-anatomy", "HARD", "DiGeorge syndrome (conotruncal anomalies, hypoplastic thymus, hypocalcemia) is associated with a microdeletion on which chromosome?", "Chromosome 22 (22q11.2)", "Chromosome 5 (5p-)", "Chromosome 11 (11p13)", "Chromosome 15 (15q11-13)", "DiGeorge syndrome is a 22q11.2 microdeletion disorder affecting the 3rd and 4th pharyngeal pouches, causing thymic and parathyroid hypoplasia."),
  q("050", "anatomy-genetics-developmental-anatomy", "HARD", "Prader-Willi and Angelman syndromes can result from a 15q11-13 microdeletion. The differing phenotypes based on parent of origin illustrate which genetic phenomenon?", "Genomic imprinting", "X-chromosome inactivation", "Anticipation", "Mitochondrial inheritance", "Genomic imprinting is an epigenetic process where the expression of an allele depends on whether it was inherited from the mother or the father."),

  // 51-55: anatomy-radiological-anatomy
  q("051", "anatomy-radiological-anatomy", "EASY", "On a normal posteroanterior (PA) chest radiograph, which cardiac chamber constitutes the majority of the right border of the cardiac silhouette?", "Right atrium", "Right ventricle", "Left ventricle", "Superior vena cava", "The right border of the heart on a PA chest X-ray is formed almost entirely by the right atrium. The right ventricle sits anteriorly."),
  q("052", "anatomy-radiological-anatomy", "MEDIUM", "A non-contrast head CT reveals a high-density collection of blood due to a torn middle meningeal artery. What characteristic shape identifies this epidural hematoma?", "Biconvex (lentiform)", "Crescent-shaped (concave)", "Diffuse hyperdensity in the basal cisterns", "Ring-enhancing lesion", "Epidural hematomas are constrained by dural attachments at cranial sutures, causing them to bulge inward and appear biconvex (lens-shaped) on CT."),
  q("053", "anatomy-radiological-anatomy", "MEDIUM", "During hysterosalpingography, normal patency of the fallopian tubes is radiologically confirmed by observing contrast spilling into which space?", "Peritoneal cavity", "Uterine cavity", "Vagina", "Broad ligament", "Contrast injected into the uterus flows through patent fallopian tubes and spills directly into the peritoneal cavity, confirming they are not blocked."),
  q("054", "anatomy-radiological-anatomy", "HARD", "On a T2-weighted sagittal MRI of the normal adult lumbar spine, the cerebrospinal fluid (CSF) within the thecal sac typically appears:", "Hyperintense (bright)", "Hypointense (dark)", "Isointense to muscle", "Isointense to cortical bone", "On T2-weighted MRI sequences, water and fluids appear bright (hyperintense). Thus, normal CSF is brilliantly hyperintense."),
  q("055", "anatomy-radiological-anatomy", "HARD", "On cerebral angiography, a saccular aneurysm at the junction of the internal carotid artery and posterior communicating artery is most likely to compress which nerve?", "Oculomotor nerve (CN III)", "Optic nerve (CN II)", "Trochlear nerve (CN IV)", "Abducens nerve (CN VI)", "A posterior communicating artery (PCoA) aneurysm classically compresses the adjacent oculomotor nerve (CN III), causing a down-and-out eye with pupillary dilation."),

  // 56-60: anatomy-surface-anatomy
  q("056", "anatomy-surface-anatomy", "EASY", "Tuffier's line, an imaginary horizontal line between the highest points of the iliac crests, typically intersects the vertebral column at which level?", "L4 spinous process", "L2 spinous process", "L3 spinous process", "S1 spinous process", "Tuffier's line reliably intersects the L4 spinous process or the L4-L5 interspace, making it the standard surface landmark for safely performing a lumbar puncture."),
  q("057", "anatomy-surface-anatomy", "MEDIUM", "McBurney's point is located at the junction of the lateral one-third and medial two-thirds of a line connecting the umbilicus to which bony prominence?", "Anterior superior iliac spine", "Anterior inferior iliac spine", "Pubic tubercle", "Ischial spine", "McBurney's point is a surface marking for the base of the appendix, located one-third of the way from the right ASIS to the umbilicus."),
  q("058", "anatomy-surface-anatomy", "MEDIUM", "The pulse of the dorsalis pedis artery is typically palpated on the dorsum of the foot just lateral to the prominent tendon of which muscle?", "Extensor hallucis longus", "Tibialis anterior", "Extensor digitorum longus", "Peroneus tertius", "The dorsalis pedis pulse is easily felt against the tarsal bones just lateral to the tendon of the extensor hallucis longus muscle."),
  q("059", "anatomy-surface-anatomy", "HARD", "In the midclavicular line, the inferior margin of the normal lung extends to which rib level during quiet respiration?", "6th rib", "4th rib", "8th rib", "10th rib", "During quiet respiration, the lung crosses the 6th rib in the midclavicular line, 8th in midaxillary, and 10th posteriorly. The pleura extends two ribs further down."),
  q("060", "anatomy-surface-anatomy", "HARD", "To optimally auscultate the closure of the aortic valve, the stethoscope should be placed at which of the following surface locations?", "Right second intercostal space at the sternal border", "Left second intercostal space at the sternal border", "Left fifth intercostal space at the midclavicular line", "Lower left sternal border at the fourth intercostal space", "Sound from the aortic valve radiates along the ascending aorta. The optimal auscultation site is the right 2nd intercostal space near the sternum."),

  // 61-65: anatomy-applied-anatomy
  q("061", "anatomy-applied-anatomy", "EASY", "Carpal tunnel syndrome presents with tingling and numbness in the thumb, index, and middle fingers. It is caused by compression of which nerve?", "Median nerve", "Ulnar nerve", "Radial nerve", "Musculocutaneous nerve", "The median nerve travels through the carpal tunnel. Compression leads to sensory changes in the lateral 3.5 digits and thenar muscle atrophy."),
  q("062", "anatomy-applied-anatomy", "MEDIUM", "Thoracic outlet syndrome frequently involves compression of the lower trunk of the brachial plexus and which associated blood vessel?", "Subclavian artery", "Axillary artery", "Internal jugular vein", "Brachiocephalic trunk", "The neurovascular bundle (lower trunk of brachial plexus and subclavian artery) passes over the first rib and can be compressed in the thoracic outlet."),
  q("063", "anatomy-applied-anatomy", "MEDIUM", "A runner develops acute anterior compartment syndrome of the leg. Which nerve is most at risk of ischemic damage in this specific compartment?", "Deep peroneal nerve", "Superficial peroneal nerve", "Tibial nerve", "Sural nerve", "The anterior compartment of the leg contains the deep peroneal (fibular) nerve. Ischemia causes weakness in dorsiflexion and sensory loss in the first web space."),
  q("064", "anatomy-applied-anatomy", "HARD", "During central venous catheterization of the internal jugular vein, the needle is typically inserted at the apex of the triangle formed by the clavicle and the two heads of which muscle?", "Sternocleidomastoid", "Omohyoid", "Scalenus anterior", "Trapezius", "Seddon's triangle is bounded by the sternal and clavicular heads of the sternocleidomastoid muscle and the clavicle. The IJV runs directly beneath the apex."),
  q("065", "anatomy-applied-anatomy", "HARD", "During an emergency surgical cricothyrotomy, the incision is made through the median cricothyroid ligament. This is located between which two cartilages?", "Thyroid and cricoid cartilages", "Cricoid cartilage and the first tracheal ring", "Hyoid bone and thyroid cartilage", "Arytenoid and cricoid cartilages", "The cricothyroid membrane connects the thyroid cartilage superiorly to the cricoid cartilage inferiorly, providing a rapid access point for emergency airways."),

  // 66-70: anatomy-upper-limb
  q("066", "anatomy-upper-limb", "EASY", "A stab wound to the lateral chest wall causes the medial border of the right scapula to protrude ('winging of the scapula'). Which nerve is injured?", "Long thoracic nerve", "Dorsal scapular nerve", "Suprascapular nerve", "Thoracodorsal nerve", "The long thoracic nerve innervates the serratus anterior. Injury paralyzes the muscle, preventing it from holding the scapula flat against the thoracic wall."),
  q("067", "anatomy-upper-limb", "MEDIUM", "A patient sustains a mid-shaft fracture of the humerus and subsequently cannot extend the wrist and fingers (wrist drop). Which nerve is compromised?", "Radial nerve", "Median nerve", "Ulnar nerve", "Axillary nerve", "The radial nerve spirals tightly around the posterior aspect of the humeral mid-shaft in the radial groove, making it highly vulnerable to stretch or transection here."),
  q("068", "anatomy-upper-limb", "MEDIUM", "A baby delivered after shoulder dystocia presents with a 'waiter's tip' posture (arm internally rotated, forearm pronated). This indicates injury to which brachial plexus roots?", "Superior trunk (C5, C6)", "Middle trunk (C7)", "Inferior trunk (C8, T1)", "Posterior cord", "Erb's palsy is an upper brachial plexus injury (C5-C6) typically caused by excessive lateral traction on the neck during birth, paralyzing shoulder abductors and external rotators."),
  q("069", "anatomy-upper-limb", "HARD", "Klumpke's palsy, often caused by grabbing a branch while falling, presents with a 'claw hand' deformity. This stretch injury affects which portion of the brachial plexus?", "Inferior trunk (C8, T1)", "Superior trunk (C5, C6)", "Lateral cord", "Axillary nerve", "Klumpke's palsy is a lower trunk (C8-T1) injury. It denervates the intrinsic hand muscles, leading to a prominent claw hand due to unopposed long flexors and extensors."),
  q("070", "anatomy-upper-limb", "HARD", "An avid cyclist complains of numbness in his ring and little fingers, and weakness in gripping. The physician suspects entrapment of which nerve within Guyon's canal?", "Ulnar nerve", "Median nerve", "Radial nerve", "Anterior interosseous nerve", "The ulnar nerve passes through Guyon's canal at the wrist. Prolonged pressure, such as resting on bicycle handlebars, can compress it, causing 'cyclist's palsy'.")
];

const dir = path.join(__dirname, 'data');
if (!fs.existsSync(dir)) fs.mkdirSync(dir);
fs.writeFileSync(path.join(dir, 'anatomy-70.json'), JSON.stringify(data, null, 2));
console.log('JSON file successfully generated at data/anatomy-70.json');
